spring:
  redis:
    host: ${QRL_REDIS_HOST:localhost}
    port: ${QRL_REDIS_PORT:6379}
  data:
    redis:
      host: ${QRL_REDIS_HOST:localhost}
      port: ${QRL_REDIS_PORT:6379}

clazs:
  ratelimiter:
    storage: redis
    redis:
      key-prefix: "qratelimiter:example:"
